config/routes.rb
Rails.application.routes.draw do
  get "/pages/:page" => "pages#show"
  resources :artworks do
    post :update_row_order, on: :collection
    collection do
      get 'catalog'
    end
  end

  

  resources :cats

  root "pages#show", page: "home"

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base

		has_and_belongs_to_many :cats, join_table: :cats_artworks

		mount_uploader :picture, PictureUploader

		include RankedModel
  		ranks :row_order

end

app/models/cat.rb
class Cat < ActiveRecord::Base

	has_and_belongs_to_many :artworks, join_table: :cats_artworks
	mount_uploader :picture, PictureUploader

end

app/models/cat_artwork.rb
class CatArtwork < ActiveRecord::Base

belongs_to :category
belongs_to :tutorial

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]

  # GET /artworks
  # GET /artworks.json
  def index
    if params[:cat_id]
      @cat_id=params[:cat_id]
      @artworks = Cat.find(@cat_id).artworks.rank(:row_order).all
    else
      @artworks = Artwork.rank(:row_order).all
    end
    
  end


 def catalog
    @artworks = Artwork.rank(:row_order).all
  end


def update_row_order
    @artwork = Artwork.find(artwork_params[:artwork_id])
    @artwork.row_order_position = artwork_params[:row_order_position]
    @artwork.save

    render nothing: true # this is a POST action, updates sent via AJAX, no view rendered
  end



  # GET /artworks/1
  # GET /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  # POST /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Disegno inserito con successo.' }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1
  # PATCH/PUT /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to artworks_url, notice: 'Disegno modificato con successo!' }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url, notice: 'Disegno eliminato!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artwork_params
      params.require(:artwork).permit(:name, :description, :picture, :row_order, :cat_id, :artwork_id, :row_order_position, {:cat_ids =>[]}) 
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to cats_path, notice: 'Categoria creata con successo.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to cats_path, notice: 'Categoria modificata con successo.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Categoria eliminata.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def show
		 render template: "pages/#{params[:page]}"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper


end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/artworks/_form.html.erb
<%= form_for(@artwork) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nome" %><br>
    <%= f.text_field :name, :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label "Descrizione" %><br>
    <%= f.text_area :description, :class=>"form-control" %>
  </div>
  <div class="field">
  <h4>Categorie</h4>
  <%= hidden_field_tag "artwork[cat_ids][]", nil %>
    <% Cat.all.each do |cat| %>
    <%= check_box_tag "artwork[cat_ids][]", cat.id, @artwork.cat_ids.include?(cat.id), id: dom_id(cat) %>
    <%= label_tag dom_id(cat), cat.name%><br>
    <% end %>
  </div>
  <div class="field">
    <%= f.label "Immagine" %><br>
    <%= f.file_field :picture, :class=>"btn btn-default" %>
  </div>
 
   <div class="actions">
    <%= f.submit "Salva", :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/artworks/catalog.html.erb
<p id="notice"><%= notice %></p>
  <div class="catmenu">
  <div class="row">
    <h1 style="text-align:center;">CATALOGO DISEGNI</h1>
<br>
 
</div>
      <h4  href="#"> Categorie/Categories</h2><br>
      <ul class="catlist">
       <% Cat.all.each do |cat| %>
        <li>
          <a  class="btn btn-info .btn-lg" href="#" onclick="$('.grid').isotope({ filter: '.cat-<%= cat.id.to_s %>' });setCategories('.cat-<%= cat.id.to_s %>')"><%= cat.name %></a>
        </li>

        <% end %>
        <li>
          <a  class="btn btn-info .btn-lg" href="#" onclick="$('.grid').isotope({ filter: '' });noCategories();">Tutte/All</a>
        </li>
      </ul>
     
    </div>

    <div class="navbar navbar-default navbar-fixed-top" style="display:none;">
      <button type="button" class="navbar-toggle btn btn-primary" data-toggle="offcanvas" data-target=".navmenu" data-canvas="body" >
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
         <span class="pull-right"><strong>CATEGORIE<br>
        CATEGORIES</strong></span>
      </button>
    </div>

<div class="container-fluid" style="margin-top:205px;">
  
  <div class="row">

<div id="masonry-container" class="transitions-enabled centered infinite-scroll col-md-11 clearfix grid">


    <% @artworks.each do |artwork| %>
       <div class="box <%= artwork.cats.map{|c| 'cat-'+c.id.to_s}.join(" ") %>">
       <a class="swipebox" rel="group" href="<%= artwork.picture %>" title="<%= artwork.name %>" onclick="hide_cats();">
         <%= image_tag(artwork.picture, :class=>"box-image") if artwork.picture.present? %>
         </a>
          <p class="box-label"><%= artwork.name %></p>
        </div>
        
    <% end %>



</div>



</div>


</div>

app/views/artworks/edit.html.erb
<h1>Editing Artwork</h1>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', artworks_path %>

app/views/artworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elenco disegni</h1>
<%= link_to 'Aggiungi Nuovo', new_artwork_path, :class=>"btn btn-info" %> <%= link_to 'Home page', "/", :class=>"btn btn-info" %>
<div class="row">


<div class="col-md-12" data-no-turbolink>
<h3>Filtra per categoria</h3>
<%= link_to "Tutte", artworks_path(),  :class=> "btn btn-warning" %>
<% Cat.all.each do |cat| %>
     
         <%= link_to cat.name, artworks_path(:cat_id=>cat.id),  :class=> "btn btn-warning" %></a>
      
 <% end %> 
</div>
  
</div data-no-turbolink>
<table class="table table-striped" id="sortable">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrizione</th>
      <th>Immagine</th>
      <th>Categorie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artworks.each do |artwork| %>
      <tr data-item-id=<%= "#{artwork.id}" %> class="item <%= artwork.cats.map{|c| 'rowcat-'+c.id.to_s}.join(" ") %>">
        <td><%= artwork.name %></td>
        <td><%= artwork.description %></td>
        <td><%= image_tag(artwork.picture, :height=>110) if artwork.picture.present? %></td>
        <td><%= artwork.cats.map{|c| c.name}.join(", ") %></td>
        <td><%= link_to 'Dettagli', artwork, :class=>"btn btn-info" %></td>
        <td><%= link_to 'Modifica/Aggiungi Categorie', edit_artwork_path(artwork), :class=>"btn btn-warning" %></td>
        <td><%= link_to 'Elimina', artwork, method: :delete, data: { confirm: 'Sei sicuro?' },  :class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/artworks/new.html.erb
<h1>Nuovo Disegno</h1>

<%= render 'form' %>

<%= link_to 'Torna a lista disegni', artworks_path, :class=>"btn btn-default" %>

app/views/artworks/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= @artwork.name %></h1>

<p>
  
  <%= @artwork.description %>
</p>
<p>
  <strong>Categorie:</strong>
  <%= @artwork.cats.map{|c| c.name}.join(", ") %>
</p>

<p>
    <%= image_tag(@artwork.picture, :height=>300) if @artwork.picture.present? %>
</p>



<%= link_to 'Modifica', edit_artwork_path(@artwork), :class=>"btn btn-warning" %>
<%= link_to 'Torna a Elenco Disegni', artworks_path, :class=>"btn btn-primary" %>
<%= link_to 'Aggiungi Nuovo', new_artwork_path, :class=>"btn btn-info" %>

app/views/cats/_form.html.erb
<div class="form-group">
  

<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nome" %><br>
    <%= f.text_field :name, :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label "Descrizione" %><br>
    <%= f.text_area :description, :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label "Immagine" %><br>
    <%= f.file_field :picture, :class=>"btn btn-default" %>
  </div>
  <div class="actions">
    <%= f.submit "Salva", :class=>"btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elenco Categorie</h1>
<%= link_to 'Aggiungi Categoria', new_cat_path, :class=>"btn btn-info" %> <%= link_to 'Home Page', "/", :class=>"btn btn-info" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome Categoria</th>
      <th>Descrizione</th>
      <th>Icona</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody> 
    <% @cats.each do |cat| %>
      <tr>
        <td><h3><%= cat.name %></h3></td>
        <td><%= cat.description %></td>
        <td><%= image_tag(cat.picture, :width=>150) if cat.picture.present? %></td>
        <td><%= link_to 'Dettagli', cat, :class=>"btn btn-info" %></td>
        <td><%= link_to 'Modifica', edit_cat_path(cat), :class=>"btn btn-warning" %></td>
        <td><%= link_to 'Elimina', cat, method: :delete, data: { confirm: 'Sei sicuro?' },  :class=>"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cats/new.html.erb
<h1>Aggiungi Categoria</h1>

<%= render 'form' %>

<%= link_to 'Torna alle Categorie', cats_path, :class=>"btn btn-primary" %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cat.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@cat.picture, :width=>200) if @cat.picture.present? %>
</p>

<%= link_to 'Modifica', edit_cat_path(@cat) %> |
<%= link_to 'Torna a lista Categorie', cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IltPin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>



  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<script src="/assets/javascripts/jquery.swipebox.js"></script>

  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12">
			<%= yield %>
		</div>
	</div>
</div>
</body>
</html>

app/views/pages/home.html.erb
  <div class="container-fluid" style="text-align:center">
  	
  	<h2>Home Page</h2>

  <p>Pannello di controllo del catalogo interattivo.</p>
  	<%= link_to "Gestione Disegni", artworks_path(),  :class=> "btn btn-warning" %>
	<%= link_to "Gestione Categorie", cats_path(),  :class=> "btn btn-warning" %>
	<%= link_to "Catalogo", "/artworks/catalog",  :class=> "btn btn-warning" %>


  </div>
  